### PR TITLE
remove peft in demo

### PR DESCRIPTION
**Pull request by arkohut**
Sorry for knowing little about this code. Close it if it is wrong.

### CODE REVIEW

**Comment by zRzRzRzRzRzRzR** [comment]
Not Know Why need this

**Comment by arkohut** [comment]
Do you guys really need open source? You told me peft is unnecessary and the code has dependencies about that. After I delete the peft dependency, you said "Not Know Why"????

https://github.com/THUDM/GLM-4/pull/37#issuecomment-2149597824

**Comment by zRzRzRzRzRzRzR** [comment]
unecessary at basic demo and necessary at finetune demo. so you need install it at finetune demo.
In basic demo, use peft because after finetune you need peft model in basic demo to infer the model.

I now understand about this. I will check this code now

**Comment by zRzRzRzRzRzRzR** [comment]
Sorry for the misunderstanding. After further communication between our colleagues and you, I have found some irregularities in the relevant code and am ready to further standardize it.
1. In the PR in the afternoon, I have set a non-mandatory PEFT requirement in requirements.txt (comment status)
2. In some demos, I have restored the method of using the most basic transformers to load the model, and retained the solution that can use the PEFT model to load.

Thank you for pointing out the error.

**Pull request closed without merging**
